= Python script for merging Bitbucket pull requests

One of the projects I'm working on uses Bitbucket Cloud. Changes are made via
pull requests. Unfortunately, Bitbucket only does non-fastforward merges when
you merge a pull request via web interface, even if it is only one commit that
needs to be merged. There is no rebase or squash option. We don't like this
because it clutters up the history with lots of unnecessary merge commits
that do not add any value. There may be cases when you want to merge a series
of commits explicitly, but most of the time, this is not what we want. We
prefer to have a nice and mostly linear history.

You can work around this limitation by pushing the feature branch the pull request
was created from directly to the target branch. Bitbucket recognizes this and
closes the pull request automatically. This also gives us rebase and squash
options. We create pull requests, keep committing on them until everything is nice
and polished, and then squash the feature branch and force-push the squashed commit
to the feature branch and the target branch.

[source]
----
usage: merge_pull.py [-h] [--target-branch TARGET_BRANCH] [--remote REMOTE]
                     [--message MESSAGE] [--assume-yes]

Merges a Bitbucket pull request. Multiple commits are squashed. The commits
are then rebased on top of upstream changes and pushed directly to the feature
branch and the target branch. Bitbucket regognizes this and marks the pull
request as merged. Then switches to the target branch and deletes the feature
branch.

optional arguments:
  -h, --help            show this help message and exit
  --target-branch TARGET_BRANCH, -t TARGET_BRANCH
                        The target_branch of the pull request (default:
                        master)
  --remote REMOTE, -r REMOTE
                        The name of the remote (default: origin)
  --message MESSAGE, -m MESSAGE
                        If commits need to be squashed, a commit message for
                        the final commit is required. You will be prompted to
                        re-use the message of the first commit on the feature
                        branch. You may then decide to enter a different
                        message (default: None)
  --assume-yes, -y      Automatic yes to prompts (default: False)
----
